### ISSUE TITLE
Issue about description of phases

### ISSUE THREAD

**Issue by Laysest** [CityBrainChallenge/KDDCup2021-CityBrainChallenge#3]
Firstly, many thanks for authors' contribution to organize the KDD cup.

I see in the source, phases are defined as integer numbers (0, 1, 2, 3). Currently, we have ['lane_speed','lane_vehicle_num'] as observation_features. 

However, how can we map the lane_vehicle_num to the green/red phases? For example, we know lane A has 2 vehicles, also the intersection is in phase 1, but we do not know lane A is in a red or green signal.

I hope I can get an array to describe phases of an intersection such as **phase 0 == ['g', 'g', ... 'r', 'r']** which should have **a same order** compared with the order in  observation_features.

You know, we can not control optimally without this information.

Thank you in advances.

Regards,
Toan

**Comment by zhyliu00** [comment]
Thank you for your suggestion. We have updated the document.

We understand your question as two points.

1. How is the lane id mapped to the index of observation features? For this part, you can refer to the format of observations at the APIs section of the documentation. This part has described each dimension of the state feature. The link can be found here. https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/APIs.html#simulation-step

2. How is each lane mapped to the signal phase? You can find the mapping between lane id and phase id in "Actions" section on the "Environment - CBEngine" page. Please refer to the following link for more details.
https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/cbengine.html#actions

Also, please note that the phase numbering starts at 1 rather than 0.

Thanks for your suggestion!

City Brain Challenge Team

**Comment by Laysest** [comment]
Many thanks for your fast support.
